#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/poverty_alleviation?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimeZone=GTM+8
#    username: root
#    password: mzb5201314
#mybatis:
#  # 扫描指定路径下的映射文件（sql）
#  mapper-locations: classpath:com/fc/mapper/*.xml
#  configuration:
#    # 加sql执行日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    # 二级缓存
#    cache-enabled: true
#    # 主键回填
#    use-generated-keys: true
#    # 驼峰映射
#    map-underscore-to-camel-case: true
#    # 懒加载
#    lazy-loading-enabled: true
#    # 积极加载
#    aggressive-lazy-loading: false
#  # 别名所在的包
#  type-aliases-package: com.fc.entity
#  # mybatis-config.xml配置文件所在的路径
##  config-location:
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poverty_alleviation?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimeZone=GTM+8
    username: root
    password: mzb5201314
mybatis:
  mapper-locations: classpath:com/fc/mapper/*.xml
  configuration:
    #加载sql执行日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启二级缓存
    cache-enabled: true
    #主键回填
    use-generated-keys: true
    #驼峰映射
    map-underscore-to-camel-case: true
    #懒加载
    lazy-loading-enabled: true
    #积极加载
    aggressive-lazy-loading: false
    #别名所在的包
    type-aliases-package: com.fc.entity


